version: "3"
services:
  web:
    build: .
    platform: linux/amd64
    image: safeware/templates:latest
    command: python3 manage.py runserver 0.0.0.0:8090
    volumes:
      - ./:/code
    ports:
      - "8090:8090"
    expose:
      - "8090"
    depends_on:
      - db
    env_file:
      - ./conf/.env
    networks:
      - django-templates-dev

  db:
    image: container-registry.oracle.com/database/enterprise:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=system
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - django-templates-dev

networks:
  django-templates-dev:
    driver: bridge

volumes:
  oracle-data:
