# Generated by Django 3.2.21 on 2023-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230829_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_mascota', models.CharField(choices=[('Gato', 'Gato'), ('Perro', 'Perro')], default='Perro', max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_mascota', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('tipo_publicacion', models.CharField(choices=[('Perdida de mascota', 'Perdida de mascota'), ('Busqueda de mascota', 'Busqueda de mascota')], default='Busqueda de mascota', max_length=255)),
            ],
        ),
    ]
