# Generated by Django 3.2.21 on 2023-09-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_publicaciones_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
