# Generated by Django 3.2.21 on 2023-09-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario_comuna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Comuna',
            new_name='comuna',
        ),
    ]
