# Generated by Django 3.2.21 on 2023-09-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_comuna_usuario_comuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='color',
        ),
    ]
