# Generated by Django 3.2.21 on 2023-09-23 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_publicaciones_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
