# Generated by Django 3.2.22 on 2023-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mascota_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/mascotas'),
        ),
    ]
