# Generated by Django 3.2.22 on 2023-10-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mascota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='es_animal',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_de_animal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
