# Generated by Django 3.2.22 on 2023-10-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20231004_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_gpt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='tipo_publicacion',
            field=models.CharField(choices=[('Perdida de mascota', 'Perdida de mascota'), ('Busqueda de mascota', 'Busqueda de mascota'), ('Presentacion de mascota', 'Presentacion de mascota')], default='Busqueda de mascota', max_length=255),
        ),
    ]
