# Generated by Django 3.2.22 on 2023-10-05 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20231004_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mi_Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_mascota', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.CharField(blank=True, max_length=255, null=True)),
                ('dueño', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
