# Generated by Django 3.2.22 on 2023-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_mi_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
