# Generated by Django 3.2.22 on 2023-10-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_mascota_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tags',
            field=models.ManyToManyField(related_name='mascotas', to='core.Tag'),
        ),
    ]
