# Generated by Django 3.2.22 on 2023-10-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_mascota_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mascotas', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
