# Generated by Django 3.2.22 on 2023-10-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20231005_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='mi_mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/mi_mascota'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/usuario'),
        ),
    ]
