# Generated by Django 3.2.22 on 2023-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20231006_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_vacuna', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_proxima_vacuna', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mi_mascota',
            name='vacunas',
            field=models.ManyToManyField(blank=True, to='core.Vacuna'),
        ),
    ]
