# Generated by Django 3.2.22 on 2023-10-23 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fichamedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.CharField(blank=True, max_length=255, null=True)),
                ('longitud', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Peluqueria', 'Peluqueria'), ('Veterinaria', 'Veterinaria'), ('Petshop', 'Petshop')], max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='foto_mascota',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='tipo_mascota',
        ),
        migrations.AddField(
            model_name='mi_mascota',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mi_mascota',
            name='es_animal',
            field=models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='mi_mascota',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mi_mascota'),
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
