# Generated by Django 3.2.22 on 2023-10-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20231023_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mi_mascota',
            name='color',
        ),
        migrations.RemoveField(
            model_name='mi_mascota',
            name='es_animal',
        ),
        migrations.RemoveField(
            model_name='mi_mascota',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='mascota',
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='foto_mascota',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='publicaciones',
            name='tipo_mascota',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Perro', 'Perro')], default='Perro', max_length=255),
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='tipo_publicacion',
            field=models.CharField(choices=[('Perdida de mascota', 'Perdida de mascota'), ('Busqueda de mascota', 'Busqueda de mascota')], default='Busqueda de mascota', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Peluqueria', 'Peluqueria'), ('Veterinaria', 'Veterinaria'), ('Petshop', 'PetShop')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_animal', models.BooleanField(blank=True, choices=[(True, 'Sí'), (False, 'No')], default=True, null=True)),
                ('tipo_de_animal', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/mascotas')),
                ('tags', models.ManyToManyField(blank=True, to='core.Tag')),
            ],
        ),
    ]
