# Generated by Django 3.2.22 on 2023-11-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20231023_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
