# Generated by Django 3.2.22 on 2023-11-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_publicaciones_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='mi_mascota',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.Tag'),
        ),
    ]
