# Generated by Django 3.2.22 on 2023-11-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_mi_mascota_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
