# Generated by Django 3.2.22 on 2023-11-14 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_similitud_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='usuario',
        ),
    ]
