# Generated by Django 3.2.22 on 2023-11-14 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_comentarios_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similitud',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentarios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
