# Generated by Django 3.2.22 on 2023-11-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20231114_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='tipo_publicacion',
            field=models.CharField(choices=[('Perdida de mascota', 'Perdida de mascota')], default='Perdida de mascota', max_length=255),
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
