# Generated by Django 3.2.22 on 2023-11-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
