# Generated by Django 3.2.22 on 2023-11-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20231128_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='token_google_maps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
